config/routes.rb
Rails.application.routes.draw do


  get "/", to: "pages#index"
  resources :topic04s
  resources :topic03s
  resources :topic02s
  resources :topics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/comments' ,to:'comments#create'
  resources :comments

  post '/comment02s' ,to:'comment02s#create'
  resources :comment02s
  #delete "/comments/#{:id}",to:"comments#destroy"
  post '/comment03s' ,to:'comment03s#create'
  resources :comment03s

  post '/comment04s' ,to:'comment04s#create'
  resources :comment04s
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  mount_uploader :picture, PictureUploader
    belongs_to :topic
    has_one_attached :avatar # 追記
end

app/models/comment02.rb
class Comment02 < ApplicationRecord
  mount_uploader :picture, PictureUploader
    belongs_to :topic02
    has_one_attached :avatar # 追記
end

app/models/comment03.rb
class Comment03 < ApplicationRecord
  mount_uploader :picture, PictureUploader
    belongs_to :topic03
    has_one_attached :avatar # 追記
end

app/models/comment04.rb
class Comment04 < ApplicationRecord
  mount_uploader :picture, PictureUploader
    belongs_to :topic04
    has_one_attached :avatar # 追記
end

app/models/topic.rb
class Topic < ApplicationRecord
   mount_uploader :picture, PictureUploader
   has_many :comments
   validates :title, presence: true
   has_one_attached :avatar # 追記

end

app/models/topic02.rb
class Topic02 < ApplicationRecord
   mount_uploader :picture, PictureUploader
   has_many :comment02s
   validates :title, presence: true
   has_one_attached :avatar # 追記
end

app/models/topic03.rb
class Topic03 < ApplicationRecord
  mount_uploader :picture, PictureUploader
  has_many :comment03s
  validates :title, presence: true
  has_one_attached :avatar # 追記
end

app/models/topic04.rb
class Topic04 < ApplicationRecord
  mount_uploader :picture, PictureUploader
  has_many :comment04s
  validates :title, presence: true
  has_one_attached :avatar # 追記
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
      @comment = Comment.new(
         topic_id: params[:comment][:topic_id],
         body: params[:comment][:body],
         picture: params[:comment][:picture] )

      if @comment.save
       redirect_to topic_path(params[:comment][:topic_id]),notice:  'コメント登録しました'
      else
       redirect_to topics_path,notice: 'コメント失敗しました'
      end
  end

  def destroy
     @comment = Comment.find(params[:id])
     @comment.destroy
     respond_to do |format|
     format.html { redirect_to topics_path, notice: 'Comment was successfully destroyed.' }
     format.json { head :no_content }
      end
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/topic02s_controller.rb
class Topic02sController < ApplicationController
  before_action :set_topic02, only: [:show, :edit, :update, :destroy]

  # GET /topic02s
  # GET /topic02s.json
  def index
    @topic02s = Topic02.all
  end

  # GET /topic02s/1
  # GET /topic02s/1.json
  def show
      @comment = Comment02.new
  end

  # GET /topic02s/new
  def new
    @topic02 = Topic02.new
  end

  # GET /topic02s/1/edit
  def edit
  end

  # POST /topic02s
  # POST /topic02s.json
  def create
    @topic02 = Topic02.new(topic02_params)

    respond_to do |format|
      if @topic02.save
        format.html { redirect_to @topic02, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic02 }
      else
        format.html { render :new }
        format.json { render json: @topic02.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topic02s/1
  # PATCH/PUT /topic02s/1.json
  def update
    respond_to do |format|
      if @topic02.update(topic02_params)
        format.html { redirect_to @topic02, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic02 }
      else
        format.html { render :edit }
        format.json { render json: @topic02.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topic02s/1
  # DELETE /topic02s/1.json
  def destroy
    @topic02.destroy
    respond_to do |format|
      format.html { redirect_to topic02s_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic02
      @topic02 = Topic02.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic02_params
      params.require(:topic02).permit(:title, :body, :picture,:avatar)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @comment = Comment.new

  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :body, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment02s_helper.rb
module Comment02sHelper
end

app/helpers/comment03s_helper.rb
module Comment03sHelper
end

app/helpers/comment04s_helper.rb
module Comment04sHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/topic02s_helper.rb
module Topic02sHelper
end

app/helpers/topic03s_helper.rb
module Topic03sHelper
end

app/helpers/topic04s_helper.rb
module Topic04sHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topic02s/_form.html.erb
<%= form_with(model: topic02, local: true) do |form| %>
  <% if topic02.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic02.errors.count, "error") %> prohibited this topic02 from being saved:</h2>

      <ul>
      <% topic02.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
   <%= form.label :picture %>
   <%= form.file_field :picture %>
  </div>

  <p>
    <%= image_tag(@topic02.picture_url) if @topic02.picture.present? %>
  </p>

   <div class="actions">
     <%= form.submit %>
   </div>
<% end %>

app/views/topic02s/edit.html.erb
<h1>Editing Topic02</h1>

<%= render 'form', topic02: @topic02 %>

<%= link_to 'Show', @topic02 ,class: 'btn02'%> |
<%= link_to 'Back', topic02s_path,class: 'btn02' %>

app/views/topic02s/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chiba North area</h1>

<table>
  <thead>

    <tr>

      <p><%= link_to 'NEW CREATE', new_topic02_path ,class: 'btn'%>
      <%= link_to 'TOP', '/' ,class: 'btn'%></p>


    </tr>
  </thead>

  <tbody >
    <% @topic02s.each do |topic02| %>
    <table >
      <tr><td>ID:<%= topic02.id %></td></tr>
      <tr><td class="title"><%= link_to topic02.title, topic02 %></td></tr>
      <tr><td><%= image_tag topic02.picture.to_s if topic02.picture.present?%></td></tr>
      <tr><td><%= topic02.body %></td></tr>
      <tr><td><%= topic02.updated_at %></td></tr>  　
      <tr><td><%= link_to 'Show', topic02 ,class: 'btn02'%>
        <%= link_to 'Edit', edit_topic02_path(topic02) ,class: 'btn02'%>
        <%= link_to 'Destroy', topic02, method: :delete, data: { confirm: 'Are you sure?' } ,class: 'btn02'%>
      </td></tr>
    </table>
    <% end %>

    <table >
      <tr><td></td></tr>
      <tr><td class="title"><%= link_to "surfpoint","https://surfhogehoge.herokuapp.com/pointsave/new"%></td></tr>
      <tr><td><%= image_tag('sf.jpeg') %></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>     　
      <tr><td><%= link_to 'Show',  "https://surfhogehoge.herokuapp.com/pointsave/new" ,class: 'btn02'%>
      </td></tr>
    </table>


  </tbody>


  <br>

app/views/topic02s/new.html.erb
<h1>New Topic02</h1>

<%= render 'form', topic02: @topic02 %>

<%= link_to 'Back', topic02s_path ,class: 'btn02'%>

app/views/topic02s/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
    <p class="title"><%= @topic02.title %></p>
</p>

<p>
  <strong>Body:</strong>
  <%= @topic02.body %>
</p>

<p>
 <strong>Picture:</strong>
  <%= image_tag(@topic02.picture_url) if @topic02.picture.present? %>
</p>

<% @topic02.comment02s.each do |comment| %>
  <table>
  <tr><td>
　<%= image_tag(comment.picture_url) if comment.picture.present? %>
  </td></tr>
  <tr><td>
    <%= comment.body%>
  </td></tr>
  <tr><td>
    <%= link_to '削除', comment, method: :delete, data: { confirm: 'Are you sure?' } ,class: 'btn02'%>
　 </td></tr>
   </table>
　 <% end %>

  <br><br><br>
  <p > <strong>コメント</strong></p>
  <%= form_for @comment do |f| %>
  <%= f.hidden_field :topic02_id, :value =>  params[:id]%>
  <P class="comment"><%= f.text_field :body %>
  <%= f.file_field :picture %>
  <%= f.submit "投稿" ,class: 'btn02'%></p>
  <%end%>
  <br>

<%= link_to 'Edit', edit_topic02_path(@topic02) ,class: 'btn02'%> |
<%= link_to 'Back', topic02s_path ,class: 'btn02'%>

app/views/topics/_form.html.erb
<%= form_with(model: topic, local: true) do |form| %>
  <% if topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% topic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
 <div class="field">
   <%= form.label :picture %>
   <%= form.file_field :picture %>
 </div>

 <p>
   <%= image_tag(@topic.picture_url) if @topic.picture.present? %>
 </p>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/topics/edit.html.erb
<h1>Editing Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Show', @topic ,class: 'btn02'%> |
<%= link_to 'Back', topics_path ,class: 'btn02'%>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ibaraki South area</h1>

<table>
  <thead>

    <tr>

    <p><%= link_to 'NEW CREATE', new_topic_path ,class: 'btn'%>
    <%= link_to 'TOP', '/' ,class: 'btn'%></p>

    </tr>
  </thead>

  <tbody >
    <% @topics.each do |topic| %>
    <table >
      <tr><td>ID:<%= topic.id %></td></tr>
      <tr><td class="title"><%= link_to topic.title, topic %></td></tr>
      <tr><td><%= image_tag topic.picture.to_s if topic.picture.present?%></td></tr>
      <tr><td><%= topic.body %></td></tr>
      <tr><td><%= topic.updated_at %></td></tr>     　
      <tr><td><%= link_to 'Show', topic ,class: 'btn02'%>
        <%= link_to 'Edit', edit_topic_path(topic) ,class: 'btn02'%>
        <%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } ,class: 'btn02'%>
      </td></tr>
    </table>
    <% end %>

    <table >
      <tr><td></td></tr>
      <tr><td class="title"><%= link_to "surfpoint","https://surfhogehoge.herokuapp.com/pointsave/new"%></td></tr>
      <tr><td><%= image_tag('sf.jpeg') %></td></tr>
      <tr><td></td></tr>
      <tr><td></td></tr>     　
      <tr><td><%= link_to 'Show',  "https://surfhogehoge.herokuapp.com/pointsave/new" ,class: 'btn02'%>
      </td></tr>
    </table>



  </tbody>


<br>

app/views/topics/new.html.erb
<h1>New Topic</h1>

<%= render 'form', topic: @topic %>

<%= link_to 'Back', topics_path ,class: 'btn02'%>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong >Title:</strong>
  <p class="title"><%= @topic.title %></p>
<p>
  <strong>Body:</strong>
  <%= @topic.body %></p>
<p>
 <strong>Picture:</strong>
  <%= image_tag(@topic.picture_url) if @topic.picture.present? %></p>


  　<% @topic.comments.each do |comment| %>
    <table>
    <tr><td>
  　<%= image_tag(comment.picture_url) if comment.picture.present? %>
    </td></tr>
    <tr><td>
      <%= comment.body%>
    </td></tr>
    <tr><td>
      <%= link_to '削除', comment, method: :delete, data: { confirm: 'Are you sure?' } ,class: 'btn02'%>
  　 </td></tr>
     </table>
  　 <% end %>

    <br><br><br>
    <p> <strong>コメント</strong></p>
    <%= form_for @comment do |f| %>
    <%= f.hidden_field :topic_id, :value =>  params[:id]%>
    <P class="comment"><%= f.text_field :body %>
    <%= f.file_field :picture %>
    <%= f.submit "投稿" ,class: 'btn02'%></p>
    <%end%>
    <br>


<%= link_to 'Edit', edit_topic_path(@topic) ,class: 'btn02'%> |
<%= link_to 'Back', topics_path ,class: 'btn02'%>