config/routes.rb
Rails.application.routes.draw do


  get "/", to: "pages#index"
  resources :topic04s
  resources :topic03s
  resources :topic02s
  resources :topics
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post '/comments' ,to:'comments#create'
  resources :comments

  post '/comment02s' ,to:'comment02s#create'
  resources :comment02s
  #delete "/comments/#{:id}",to:"comments#destroy"
  post '/comment03s' ,to:'comment03s#create'
  resources :comment03s

  post '/comment04s' ,to:'comment04s#create'
  resources :comment04s
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  mount_uploader :picture, PictureUploader
    belongs_to :topic
    has_one_attached :avatar # 追記
end

app/models/comment02.rb
class Comment02 < ApplicationRecord
  mount_uploader :picture, PictureUploader
    belongs_to :topic02
    has_one_attached :avatar # 追記
end

app/models/comment03.rb
class Comment03 < ApplicationRecord
  mount_uploader :picture, PictureUploader
    belongs_to :topic03
    has_one_attached :avatar # 追記
end

app/models/comment04.rb
class Comment04 < ApplicationRecord
  mount_uploader :picture, PictureUploader
    belongs_to :topic04
    has_one_attached :avatar # 追記
end

app/models/topic.rb
class Topic < ApplicationRecord
   mount_uploader :picture, PictureUploader
   has_many :comments
   validates :title, presence: true
   has_one_attached :avatar # 追記

end

app/models/topic02.rb
class Topic02 < ApplicationRecord
   mount_uploader :picture, PictureUploader
   has_many :comment02s
   validates :title, presence: true
   has_one_attached :avatar # 追記
end

app/models/topic03.rb
class Topic03 < ApplicationRecord
  mount_uploader :picture, PictureUploader
  has_many :comment03s
  validates :title, presence: true
  has_one_attached :avatar # 追記
end

app/models/topic04.rb
class Topic04 < ApplicationRecord
  mount_uploader :picture, PictureUploader
  has_many :comment04s
  validates :title, presence: true
  has_one_attached :avatar # 追記
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment02s_helper.rb
module Comment02sHelper
end

app/helpers/comment03s_helper.rb
module Comment03sHelper
end

app/helpers/comment04s_helper.rb
module Comment04sHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/topic02s_helper.rb
module Topic02sHelper
end

app/helpers/topic03s_helper.rb
module Topic03sHelper
end

app/helpers/topic04s_helper.rb
module Topic04sHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Seasidetowns</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<div id="bg">


<div class="main">
  <h1 >Sea Side Town Information</h1>
  <h2 class="subtitle">Program is a service that you can post picture and information.</h2>
</div>
    <p style="display: inline;">
      <table class="menu">
      <tr><td><span>Ibaraki South area</span></td></tr>
      <tr><td>
      <%= link_to topics_path do %>
      <%= image_tag "is.png"%>
      <% end %>
      </td></tr>
      </table>
      <table class="menu">
      <tr><td><span>Chiba North area</span></td></tr>
      <tr><td>
      <%= link_to topic02s_path do %>
      <%= image_tag "cn.png"%>
      <% end %>
      </td></tr>
      </table>
      <table class="menu">
      <tr><td><span>Chiba South area</span></td></tr>
      <tr><td>
      <%= link_to topic03s_path do %>
      <%= image_tag "cs.png"%>
      <% end %>
      </td></tr>
      </table>
      <table class="menu">
      <tr><td><span>Shonan area</span></td></tr>
      <tr><td>
      <%= link_to topic04s_path do %>
      <%= image_tag "s.png"%>
      <% end %>
      </td></tr>
      </table>

     </p>
</div>